### ISSUE TITLE
Tests fail on 5.30.3 because of mis-declared dependency version.

### ISSUE THREAD

**Issue by DrHyde** [houseabsolute/DateTime-Locale#35] opened 2023-02-05 13:23 UTC
See the failure [here](https://cirrus-ci.com/task/5116981456666624).

`version-check.t` fails thus:

```
Test2 version 1.302167 required--this is only version 1.302162 at /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm line 9.
BEGIN failed--compilation aborted at /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm line 9.
Compilation failed in require at t/version-check.t line 5.
BEGIN failed--compilation aborted at t/version-check.t line 5.
```

NB that this is a compile-time error, not an actual test failure. In `TEST_REQUIRES` you have:

```
    "Test2::V0" => 0,
    ...
    "Test::More" => "1.302015",
```

so it looks like the _declared_ version dependency is satisfied (my 1.302162 is more recent than 1.302015), and that any "fresh out of the box" 5.30.x will be affected.

**Comment by autarch** [comment] 2023-02-05 15:27
This is coming from Test2::Plugin::NoWarnings, not DateTime::Locale:

```
Test2 version 1.302167 required--this is only version 1.302162 at /System/Library/Perl/Extras/5.30/Test2/Plugin/NoWarnings.pm line 9.
```

But the requirement in the Test2-Plugin-NoWarnings distro is for Test2 1.302167. So I don't understand why this wasn't installed for you.

**Comment by autarch** [comment] 2023-02-19 22:03
I'm going to close this since whatever's going on I'm quite sure it's not a bug in DateTime-Locale.

**Closed as completed by autarch** 2023-02-19 22:03 UTC
